package core;

import java.util.Scanner;

public class Ui {

    // user input
    private static final Scanner sc = new Scanner(System.in);

    public static String getCommand() {
        return sc.hasNextLine() ? sc.nextLine() : null;
    }

    public static boolean missingInput() {
        return !sc.hasNextLine();
    }

    /**
     * Prints output generated by the bot.
     * @param output string of output to be printed
     */
    public static void print(String output) {
        System.out.println("____________________________________________________________");
        System.out.println(output);
        System.out.println("____________________________________________________________");
        System.out.println();
    }
}
