package duke.command;

import duke.core.Storage;
import duke.core.TaskList;
import duke.core.Ui;

/**
 * A template class for different commands generated by the Parser during the usage of the Duke programme.
 */
public abstract class Command {

    public abstract void execute(TaskList tasks, Storage storage, Ui ui);

}
