/**
 * Handles exceptions generated by application.
 */

public class DukeException extends Exception {
    /**
     * Constructor for DukeExcpetion.
     * @param msg Contains error message.
     */
    public DukeException(String msg) {
        super(msg);
    }
}
