import java.util.Scanner;
import java.util.stream.Stream;

public class IPbot {

    /**
     * Entry point of the program.
     * @param args command line arguments
     */
    public static void main(String[] args) {
        print("Hello from iPbot, what can I do for you?");

        final Scanner sc = new Scanner(System.in);

        Stream.generate(sc::nextLine)
            .takeWhile(input -> !"bye".equals(input))
            .forEach(IPbot::print);

        sc.close();
        print("Goodbye!");
    }

    /**
     * Prints output generated by the bot.
     * @param output string of output to be printed
     */
    public static void print(String output) {
        System.out.println("____________________________________________________________");
        System.out.println(output);
        System.out.println("____________________________________________________________");
        System.out.println();
    }
}
