import java.util.ArrayList;
import java.util.Scanner;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class IPbot {

    // command strings
    private static final String EXIT_CMD = "bye";
    private static final String LIST_CMD = "list";
    private static final String DONE_CMD = "done ";

    /**
     * Entry point of the program.
     * @param args command line arguments
     */
    public static void main(String[] args) {
        print("Hello from iPbot, what can I do for you?");

        // user input
        final Scanner sc = new Scanner(System.in);

        // task list
        final ArrayList<Task> tasks = new ArrayList<>();

        Stream.generate(sc::nextLine)
            .takeWhile(input -> !EXIT_CMD.equals(input))
            .forEach(input -> {
                final String output;
                if (LIST_CMD.equals(input)) {
                    // list tasks
                    output = tasks.isEmpty()
                            ? "No tasks added."
                            : tasks.stream()
                                .map(new Function<Task, String>() {
                                    int id = 1;
                                    public String apply(Task t) {
                                        return String.format("%d. %s", id++, t.toString());
                                    }
                                })
                                .collect(Collectors.joining("\n"));
                } else if (input.startsWith(DONE_CMD)) {
                    // mark a task as done
                    final int id = Integer.parseInt(input.substring(DONE_CMD.length()));
                    final Task toComplete = tasks.get(id - 1);
                    if (toComplete.getDoneStatus()) {
                        // already done
                        output = "Task already done:\n" + toComplete;
                    } else {
                        // mark as done
                        toComplete.markAsDone();
                        output = "Task done:\n" + toComplete;
                    }
                } else {
                    // add task
                    tasks.add(new Task(input));
                    output = "added: " + input;
                }
                print(output);
            });

        sc.close();
        print("Goodbye!");
    }

    /**
     * Prints output generated by the bot.
     * @param output string of output to be printed
     */
    public static void print(String output) {
        System.out.println("____________________________________________________________");
        System.out.println(output);
        System.out.println("____________________________________________________________");
        System.out.println();
    }
}
