package duke.task;

/**
 * Enumerates through the types of Tasks.
 *
 * It also provides methods to append each task type with an identifier and decode them.
 */
public enum TaskType {
    DEADLINE("ID_D"),
    EVENT("ID_E"),
    TODO("ID_T");

    private static final String IDENTIFIER_DELIMITER = " :: ";

    private final String id;

    TaskType(String id) {
        this.id = id;
    }

    /**
     * Appends an identifier to a task's representation.
     *
     * @param storageString Task's storage representation.
     * @param taskType Task's TaskType.
     * @return Storage string appended with the task's identifier.
     * @throws TaskTypeDecodeException If the given taskType is invalid.
     */
    public static String appendIdentifier(String storageString, TaskType taskType) throws TaskTypeDecodeException {
        return taskType.id + IDENTIFIER_DELIMITER + storageString;
    }

    /**
     * Decodes a storage string that was created by `appendIdentifier()`.
     *
     * @param storageString Storage string created by `appendIdentifier()`.
     * @return The found TaskType.
     * @throws TaskTypeDecodeException If the storage string cannot be delimited or TaskType cannot be found.
     */
    public static TaskType decodeTaskType(String storageString) throws TaskTypeDecodeException {
        try {
            String identifier = storageString.split(IDENTIFIER_DELIMITER)[0];
            if (identifier.equals(TaskType.DEADLINE.id)) {
                return TaskType.DEADLINE;
            } else if (identifier.equals(TaskType.EVENT.id)) {
                return TaskType.EVENT;
            } else if (identifier.equals(TaskType.TODO.id)) {
                return TaskType.TODO;
            } else {
                throw new TaskTypeDecodeException("Unknown task type");
            }
        } catch (IndexOutOfBoundsException e) {
            throw new TaskTypeDecodeException("Invalid storage string.");
        }
    }

    /**
     * Removes the identifier appended by `appendIdentifier()`.
     *
     * @param input String generated by `appendIdentifier()`.
     * @param tasktype The found TaskType.
     * @return String without the appended indentifier.
     * @throws TaskTypeDecodeException If the given string is invalid.
     */
    public static String getStorageLine(String input, TaskType tasktype) throws TaskTypeDecodeException {
        int start = tasktype.id.length() + IDENTIFIER_DELIMITER.length();
        try {
            StringBuilder string = new StringBuilder();
            for (int i = start; i < input.length(); i++) {
                string.append(input.charAt(i));
            }
            return string.toString();
        } catch (IndexOutOfBoundsException e) {
            throw new TaskTypeDecodeException("Storage string has been malformed.");
        }
    }
}
