package exceptions;

/**
 * Parent class of all exceptions generated by iPbot.
 */
public class IPException extends Exception{
    public IPException(String message) {
        super(message);
    }
}
