package exceptions;

/**
 * Parent class of all exceptions generated by iPbot.
 */
public class IpException extends Exception {
    public IpException(String message) {
        super(message);
    }
}
