package duke;

public enum CommandType {
    HELP,
    TODO,
    DEADLINE,
    EVENT,
    LIST,
    DONE,
    DELETE,
    BYE,
    INVALID_IS_EMPTY,
    INVALID_COMMAND,
    INVALID_EMPTY_DESCRIPTION,
    INVALID_DEADLINE_NO_BY,
    INVALID_EVENT_NO_START_END
}
