package duke;

public enum CommandType {
    HELP,
    TODO,
    DEADLINE,
    EVENT,
    LIST_ALL_TASKS,
    LIST_ALL_DONE,
    LIST_ALL_NOT_DONE,
    LIST_ALL_TODOS,
    LIST_ALL_DEADLINES,
    LIST_ALL_EVENTS,
    LIST_BY_KEYWORD,
    DONE,
    DELETE,
    BYE,
    INVALID_IS_EMPTY,
    INVALID_COMMAND,
    INVALID_EMPTY_DESCRIPTION,
    INVALID_DEADLINE_NO_BY,
    INVALID_EVENT_NO_START_END
}
